const DEFAULT_API_BASE_URL = "http://localhost:8080";

const API_BASE_URL = globalThis.APP_CONFIG?.API_BASE_URL || DEFAULT_API_BASE_URL;
const BOOKING_DATA_SOURCE = globalThis.APP_CONFIG?.BOOKING_DATA_SOURCE || "fixture";
const USE_BOOKING_FIXTURES = BOOKING_DATA_SOURCE !== "api";

export { API_BASE_URL, BOOKING_DATA_SOURCE, USE_BOOKING_FIXTURES };
